x-veld:
  code:
    description: "Creating a spacy config by encapsulating `init config` ( 
      https://spacy.io/api/cli#init-config ) and `init fill-config` ( 
      https://spacy.io/api/cli#init-fill-config ) . The output is ai config file used for training; 
      see more here: https://spacy.io/usage/training/#config"
    topic:
      - "NLP"
      - "Machine Learning"

    output:
      - volume: /veld/output/
        file_type: "cfg"
        environment_var: out_spacy_config
        content: "spacy training config"
        description: "See https://spacy.io/usage/training/#config"

    config:
      - environment_var: lang
        description: "See https://spacy.io/api/cli#init-config"
        var_type: str
      - environment_var: tagger
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: parser
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: ner
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: entity_linker
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: entity_ruler
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: textcat
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: textcat_multilabel
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: lemmatizer
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: trainable_lemmatizer
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: morphologizer
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: attribute_ruler
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: senter
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: sentencizer
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: tok2vec
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: transformer
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: optimize_efficiency
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: optimize_accuracy
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: gpu
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true
      - environment_var: pretraining
        description: "See https://spacy.io/api/cli#init-config"
        var_type: bool
        default: false
        optional: true

services:
  veld_create_config:
    build: .
    working_dir: /veld/code/
    command: /veld/code/create_config.sh
    volumes:
      - ./src/:/veld/code/
      - ./data/configs/:/veld/output/
    environment:
      out_config_file: null
      lang: de
      tagger: false
      parser: false
      ner: false
      entity_linker: false
      entity_ruler: false
      textcat: false
      textcat_multilabel: false
      lemmatizer: false
      trainable_lemmatizer: false
      morphologizer: false
      attribute_ruler: false
      senter: false
      sentencizer: false
      tok2vec: false
      transformer: false
      optimize_efficiency: null
      optimize_accuracy: null
      gpu: false
      pretraining: false

